version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis_pass
    entrypoint: redis-server --appendonly yes --requirepass 'redis_pass'
  
  app:
    build:
      context: .
    volumes:
      - .:/cep-event-driven
    ports:
      - '4567:4567'
    tty: true

#  postgres:  
#
#  backend:
#    image: ruby:3.0.0
#    volumes:
#      - ./:/home/user/
#    ports:
#      - '4567:4567'
#    tty: true
  
